[package]
name = "sh-exec"
version = "0.1.2"
edition = "2024"
license = "Unlicense"
author = "Christof Fetzer"
description = "Build check_cpufeatures"

[dependencies]
shells = "0.2.0"
colored = "3.0.0"