[package]
name = "sh-exec"
version = "0.1.3"
edition = "2024"
license = "Unlicense"
author = "Christof Fetzer"
description = "Set of functions and macros to write more concise rust scripts."

[dependencies]
shells = "0.2.0"
colored = "3.0.0"