[package]
authors = ["Christof Fetzer"]
categories = ["development-tools::build-utils"]
description = "Set of functions and macros to write more concise Rust scripts."
documentation = "https://docs.rs/sh-exec"
edition = "2024"
homepage = "https://github.com/christoffetzer/shell-exec"
keywords = ["script", "exec", "sh-exec"]
license = "MIT"
name = "sh-exec"
readme = "README.md"
repository = "https://github.com/christoffetzer/shell-exec"
version = "0.2.0"

[dependencies]
anyhow = "1"
colored = "3.0.0"
env_logger = "0.11.8"
log = "0.4.27"
shells = "0.2.0"
